import { Coach } from '../domain/entities/coach.entity.js'

export const MOCK_COACHES: Coach[] = [
  new Coach(
    'coach-1',
    'María García',
    'maria.garcia@gym.com',
    '555-0101',
    'hashed_password_1',
    'male',
    new Date('2000-01-15'),
    new Date('2024-01-15'),
    [
      { id: 'spec-1', name: 'Yoga', description: 'Especialista en yoga y meditación' },
      { id: 'spec-2', name: 'Pilates', description: 'Instructor certificado en Pilates' },
    ],
    true,
    'Instructora de yoga con más de 8 años de experiencia. Especializada en técnicas de relajación y flexibilidad.',
    2,
    '/img/entrenadores/Maria.jpg',
    [],
    new Date('2024-01-15'),
  ),
  new Coach(
    'coach-2',
    'Carlos Ruiz',
    'carlos.ruiz@gym.com',
    '555-0102',
    'hashed_password_2',
    'male',
    new Date('1999-02-20'),
    new Date('2024-02-20'),
    [
      { id: 'spec-3', name: 'CrossFit', description: 'Entrenador certificado en CrossFit' },
      {
        id: 'spec-4',
        name: 'Weightlifting',
        description: 'Especialista en levantamiento de pesas',
      },
    ],
    true,
    'Entrenador de alto rendimiento especializado en CrossFit y levantamiento de pesas. Ex-atleta competitivo.',
    6,
    '/img/entrenadores/Carlos.jpg',
    [],
    new Date('2024-02-20'),
  ),
  new Coach(
    'coach-3',
    'Ana López Martínez',
    'ana.lopez@gym.com',
    '555-0103',
    'hashed_password_3',
    'female',
    new Date('2005-03-10'),
    new Date('2024-03-10'),
    [
      { id: 'spec-5', name: 'Zumba', description: 'Instructora certificada en Zumba' },
      { id: 'spec-6', name: 'Cardio Dance', description: 'Especialista en bailes aeróbicos' },
    ],
    true,
    'Instructora de bailes fitness con energía contagiosa. Especializada en crear rutinas divertidas y efectivas.',
    5,
    '/img/entrenadores/Anna.jpg',
    [],
    new Date('2024-03-10'),
  ),
  new Coach(
    'coach-4',
    'Miguel Torres',
    'miguel.torres@gym.com',
    '555-0104',
    'hashed_password_4',
    'male',
    new Date('1990-04-05'),
    new Date('2024-04-05'),
    [
      { id: 'spec-7', name: 'Boxing', description: 'Entrenador de boxeo profesional' },
      { id: 'spec-8', name: 'MMA', description: 'Instructor de artes marciales mixtas' },
    ],
    true,
    'Ex-boxeador profesional con amplia experiencia en deportes de combate. Enfoque en técnica y disciplina.',
    10,
    '/img/entrenadores/Juan.jpg',
    [],
    new Date('2024-04-05'),
  ),
  new Coach(
    'coach-5',
    'Laura Fernández',
    'laura.fernandez@gym.com',
    '555-0105',
    'hashed_password_5',
    'female',
    new Date('1995-05-12'),
    new Date('2024-05-12'),
    [
      { id: 'spec-9', name: 'Spinning', description: 'Instructora certificada en Spinning' },
      { id: 'spec-10', name: 'Cycling', description: 'Especialista en ciclismo indoor' },
    ],
    true,
    'Ciclista apasionada con certificaciones en spinning y ciclismo indoor. Especializada en entrenamientos de resistencia.',
    7,
    '/img/entrenadores/Elizabeth.jpg',
    [],
    new Date('2024-05-12'),
  ),
]
